export default {
    "zhCN": "Simplified chinese",
    "zhTW": "Fan'ti chinese",
    "enUS": "English",
    "jaJP": "Japanese",
    "koKR": "Korean",
    "rotation": "Rotation",
    "windMode": "Wind Mode",
    "upDown": "up/down",
    "leftRight": "left/right",
    "threeD": "3D",
    "cancle": "cancle",
    "sleep": "sleep",
    "natural": "natural",
    "normal": "normal",
    "eco": "ECO",
    "addDevice": "Add device",
    "add": "Add",
    "rename": "RENAME",
    "delete": "DELETE",
    "name": "Name",
    "confirm": "CONFIRM",
    "enterDeviceName": "Please enter the device name",
    "selectDeviceTip": "Please select the device first",
    "openDeviceTip": "Please turn on the device first",
};