export default {
    "zhCN": "Simplified chinese",
    "zhTW": "Fan'ti chinese",
    "enUS": "English",
    "jaJP": "Japanese",
    "koKR": "Korean",
    "rotation": "Rotation",
    "windMode": "Wind Mode",
    "upDown": "up/down",
    "leftRight": "left/right",
    "threeD": "3D",
    "cancle": "cancle",
    "sleep": "sleep",
    "natural": "natural",
    "normal": "normal",
    "eco": "ECO",
    "addDevice": "Add device",
    "add": "Add",
    "rename": "RENAME",
    "delete": "DELETE",
    "name": "Name",
    "confirm": "CONFIRM",
    "enterDeviceName": "Please enter the device name",
    "selectDeviceTip": "Please select the device first",
    "openDeviceTip": "Please turn on the device first",
    "next": "Next",
    "skip": "Skip",
    "finish": "Finish",
    "previous": "Previous",
    "step1": "First, add the device. Go to the add device page",
    "step2": "After adding the device successfully, wake up the pop-up window and select the device to control",
    "step3": "Tutn on device switch"
};