export default {
    "zhCN": "簡体中国語",
    "zhTW": "繁体中国語",
    "enUS": "英語",
    "jaJP": "日本語",
    "koKR": "韓国語",
    "rotation": "ループ",
    "windMode": "モード",
    "upDown": "上下",
    "leftRight": "左右",
    "threeD": "3D",
    "cancle": "キャンセル",
    "sleep": "眠りの風",
    "natural": "自然の風",
    "normal": "普通の風",
    "eco": "スマートフォン",
    "addDevice": "デバイスを追加",
    "add": "追加",
    "rename": "名を変える",
    "delete": "削除",
    "name": "名前",
    "confirm": "を選択します",
    "enterDeviceName": "デバイス名を入力してください。",
    "selectDeviceTip": "まず設備を選んでください",
    "openDeviceTip": "先に設備を開けてください",
};