export default {
    "zhCN": "중국어",
    "zhTW": "중국어 번체",
    "enUS": "영어",
    "jaJP": "일본어",
    "koKR": "한국어",
    "rotation": "순환",
    "windMode": "모드",
    "upDown": "위아래",
    "leftRight": "왼쪽오른쪽",
    "threeD": "3D",
    "cancle": "취소",
    "sleep": "수면풍",
    "natural": "자연풍",
    "normal": "정상풍",
    "eco": "지능풍",
    "addDevice": "장치 추가",
    "add": "추가",
    "rename": "개명",
    "delete": "삭제",
    "name": "이름",
    "confirm": "확정",
    "enterDeviceName": "장치 이름을 입력하십시오",
    "selectDeviceTip": "우선 장치 선택",
    "openDeviceTip": "우선 설비를 열어 주십시오",
};