export default {
    "language": "언어",
    "zhCN": "중국어",
    "zhTW": "중국어 번체",
    "enUS": "영어",
    "jaJP": "일본어",
    "koKR": "한국어",
    "rotation": "순환",
    "windMode": "모드",
    "upDown": "위아래",
    "leftRight": "왼쪽오른쪽",
    "threeD": "3D",
    "cancle": "취소",
    "sleep": "수면풍",
    "natural": "자연풍",
    "normal": "정상풍",
    "eco": "지능풍",
    "device": "설비",
    "addDevice": "장치 추가",
    "add": "추가",
    "rename": "개명",
    "delete": "삭제",
    "name": "이름",
    "confirm": "확정",
    "enterDeviceName": "장치 이름을 입력하십시오",
    "selectDeviceTip": "우선 장치 선택",
    "openDeviceTip": "우선 설비를 열어 주십시오",
    "next": "다음 단계",
    "skip": "건너뛰다",
    "finish": "완성",
    "previous": "전보",
    "step1": "우선 설비를 첨가하고 장치 추가 페이지 추가",
    "step2": "장치를 성공적으로 첨가하면 탄창 선택 장치를 깨우면 제어할 수 있다",
    "step3": "장치 스위치",
    "sameDevice": "장치 이름이나 장치 인코딩이 같거나 새로 증가할 수 없습니다",
    "selectDevice": "장치 선택"
};