export default {
    "language": "언어",
    "zhCN": "중국어",
    "zhTW": "중국어 번체",
    "enUS": "영어",
    "jaJP": "일본어",
    "koKR": "한국어",
    "rotation": "순환",
    "windMode": "모드",
    "upDown": "상하회전",
    "leftRight": "좌우회전",
    "threeD": "입체회전",
    "cancle": "회전정지",
    "sleep": "수면풍",
    "natural": "자연풍",
    "normal": "일반풍",
    "eco": "온도감지",
    "device": "설비",
    "addDevice": "장치 추가",
    "add": "추가",
    "rename": "개명",
    "delete": "삭제",
    "name": "이름",
    "confirm": "확정",
    "enterDeviceName": "장치 이름을 입력하십시오",
    "selectDeviceTip": "우선 장치 선택",
    "openDeviceTip": "우선 설비를 열어 주십시오",
    "next": "다음단계",
    "skip": "건너뛰기",
    "finish": "확인",
    "previous": "이전",
    "step1": "설정을 클릭하고 연결 할 기기를 등록한다.",
    "step2": "기기를 성공적으로 등록하면 [장치선택]을 눌러 기기 선택 후 사용할 수 있습니다. ",
    "step3": "전원 스위치",
    "sameDevice": "장치 이름이나 장치 인코딩이 같거나 새로 증가할 수 없습니다",
    "selectDevice": "장치 선택",
    "tips": "참고",
    "tipText": "제품에 전원을 연결하고 10분 안에 기기를 등록해주세요. 시간이 지나면 기기를 등록/추가할 수 없습니다. 전원을 껏다가 켠 후 다시 시도해주세요.",
    "iKnow": "확인",
    "noPrompt": "힌트 없음",
    "openBLETip": "블루투스 열어주세요.",
    "noSupportBLEAdv": "장치는 블루투스 방송을 지원하지 않습니다"
};