export default {
    "zhCN": "中文简体",
    "zhTW": "中文繁体",
    "enUS": "英语",
    "jaJP": "日语",
    "koKR": "韩语",
    "rotation": "循环",
    "windMode": "模式",
    "upDown": "上下",
    "leftRight": "左右",
    "threeD": "3D",
    "cancle": "取消",
    "sleep": "睡眠风",
    "natural": "自然风",
    "normal": "正常风",
    "eco": "智能风",
    "addDevice": "添加设备",
    "add": "添加",
    "rename": "改名",
    "delete": "删除",
    "name": "名称",
    "confirm": "确定",
    "enterDeviceName": "请输入设备名称",
    "selectDeviceTip": "请先选择设备",
    "openDeviceTip": "请先开启设备",
};