export default {
    "zhCN": "中文簡體",
    "zhTW": "中文繁體",
    "enUS": "英語",
    "jaJP": "日語",
    "koKR": "韓語",
    "rotation": "循環",
    "windMode": "模式",
    "upDown": "上下",
    "leftRight": "左右",
    "threeD": "3D",
    "cancle": "取消",
    "sleep": "睡眠風",
    "natural": "自然風",
    "normal": "正常風",
    "eco": "智能風",
    "addDevice": "添加設備",
    "add": "添加",
    "rename": "改名",
    "delete": "刪除",
    "name": "名稱",
    "confirm": "確定",
    "enterDeviceName": "請輸入設備名稱",
    "selectDeviceTip": "請先選擇設備",
    "openDeviceTip": "請先開啓設備",
};